<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>dbrun.log</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <!--<dict>
                <key>begin</key>
                <string>[┌]</string>
                <key>end</key>
                <string>[├]</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>[\w]</string>
                        <key>name</key>
                        <string>string.quoted</string>
                    </dict>
                </array>
            </dict>-->
            <dict>
                <key>match</key>
                <string>[│┌┐├┤└┘─]</string>
                <key>name</key>
                <string>keyword.other.sql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\[(\d*)\/(\d*)\]</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>string.parameter.import.autoit</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.parameter.import.autoit</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\[(\d*)\]</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\d*) ms</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
        </array>
        <key>uuid</key>
        <string>ab259404-3072-4cd4-a943-7cbbd32e373f</string>
    </dict>
</plist>